import { GridColumns } from "@mui/x-data-grid";

export const CmplColumn:GridColumns=[
    {field:'sno',flex:1,headerName:'S.No'},
    {field:'itemcode',flex:1,headerName:'ItemCode'},
    {field:'materialcode',flex:1,headerName:'MaterialCode'},
    {field:'noun',flex:1,headerName:'Noun'},
    {field:'value',flex:1,headerName:'Value'},
    {field:'characteristic',flex:1,headerName:'Characteristic'},
    {field:'legacy',flex:1,headerName:'legacy'},
    {field:'legacy2',flex:1,headerName:'Legacy2'},
    {field:'longdesc',flex:1,headerName:'Longdesc'},
    {field:'uom',flex:1,headerName:'UOM'},
    {field:'squence',flex:1,headerName:'Squence'},
    {field:'shortdesc',flex:1,headerName:'Shortdesc'},
    {field:'modifier',flex:1,headerName:'Modifier'},
    {field:'shortSquence',flex:1,headerName:'ShortSquence'},
    {field:'additionalinfo',flex:1,headerName:'Additionalinfo'},
]

// "id": 1,
//     "sno": 1,
//     "itemcode": "SPN0061172",
//     "materialcode": "4122544",
//     "noun": "ABRASIVE",
//     "value": "EMERY",
//     "characteristic": "TYPE",
//     "legacy2": null,
//     "longdesc": "ABRASIVE,SHEET,TYPE:EMERY PAPER",
//     "uom": null,
//     "legacy": "EMMRY PAPER",
//     "squence": 1,
//     "shortdesc": "ABRSV SHT,EMRY PAPER",
//     "modifier": "SHEET",
//     "shortSquence": 1,
//     "additionalinfo": null